### ISSUE TITLE
"Petra_Kanini.mp3" should not be hard coded in audioWrapper.js

### ISSUE THREAD

**Issue by raae** [olavea/gatsby-theme-jam-trixie-hoods-and-unicorn-lillis-revenge-on-the-pirate-princess#10]
There are two possible solutions at this point: 

1. Grab the "first" audio file by replacing `relativePath: { eq: "Petra_Kanini.mp3" }` with `sourceInstanceName: {eq: "audio"}`. This will grab the only audio file in the project. This solution will break if there is more than one audio file.

2. Add a theme option, but not completely sure how to get that into the static query. Maybe use it in `onCreateNode` and add a `isMainAudio` flag?

**Comment by raae** [comment]
If @olavea does this task I think solution 1 is good enough.

**Comment by olavea** [comment]
I also think solution 1 is good enough for me. 😄 👍
