### ISSUE TITLE
Add swipe navigation to page flipper

### ISSUE THREAD

**Issue by raae** [olavea/gatsby-theme-jam-trixie-hoods-and-unicorn-lillis-revenge-on-the-pirate-princess#15]
Let the user swipe pages with touch.

**Comment by raae** [comment]
Up for grabs @testower if you want

**Comment by testower** [comment]
Cheers. How fancy do we want this to be? Should the next/previous page be previewed/rendered during the swipe?

**Comment by raae** [comment]
> Cheers. How fancy do we want this to be? Should the next/previous page be previewed/rendered during the swipe?

Not as a first solution.

**Comment by testower** [comment]
> Not as a first solution.

Got it. I guess we still want a minimum of visual feedback, so I might just come up with something simple, unless you already have some ideas.

**Comment by raae** [comment]
In my kindle, the only feedback is the page changing. But you could look at page transitions as it could be nice for all the types of navigation.

**Comment by testower** [comment]
> In my kindle, the only feedback is the page changing. But you could look at page transitions as it could be nice for all the types of navigation.

I see, maybe we should do page transitions as a dedicated task then.

**Comment by raae** [comment]
> > In my kindle, the only feedback is the page changing. But you could look at page transitions as it could be nice for all the types of navigation.
> 
> I see, maybe we should do page transitions as a dedicated task then.

Seems like a good idea.
