### ISSUE TITLE
Use Helmet to add site title and other metadata to the site

### ISSUE THREAD

**Issue by raae** [olavea/gatsby-theme-jam-trixie-hoods-and-unicorn-lillis-revenge-on-the-pirate-princess#16]
Create a SEO component and use it in the page template. 

[SEO component example](https://github.com/gatsbyjs/gatsby/blob/master/themes/gatsby-theme-blog/src/components/seo.js)
[SEO component used in post component](https://github.com/gatsbyjs/gatsby/blob/master/themes/gatsby-theme-blog/src/components/post.js)

**Comment by olavea** [comment]
"gatsby develop" worked 
"gatsby build" worked 
Netlify Deploy failed
Netlify Checks in github failed when I tried to make a pull request.

But the error message I could find was only: " Error running command: Build script returned non-zero exit code: 1"

**Comment by olavea** [comment]
Seems to be working after I played around with my git work flow
