### ISSUE TITLE
Shorter theme name that starts with "gatsby-theme"

### ISSUE THREAD

**Issue by raae** [olavea/gatsby-theme-jam-trixie-hoods-and-unicorn-lillis-revenge-on-the-pirate-princess#2]
I recommend "gatsby-theme-picture-book". 

You can also add a prefix to npm packages. I add "@raae" as a brand name. See https://www.npmjs.com/package/@raae/gatsby-remark-oembed

It needs to be updated in `theme/package.json`, `demo/package.json`, and `demo/gatsby-config.js`. Also, it would be nice if this repo on GitHub was renamed.

**Comment by olavea** [comment]
Ok, I like "gatsby-theme-childrens-picture-book"

https://www.npmjs.com/package/@olavea/gatsby-theme-childrens-picture-book

**Comment by olavea** [comment]
I will wait with this:
"Also, it would be nice if this repo on GitHub was renamed."
Because maybe it will mess up my contributions

**Comment by olavea** [comment]
I did this:
"Also, it would be nice if this repo on GitHub was renamed."

and git clone https://github.com/olavea/gatsby-theme-childrens-picture-book.git

into the new directory 2.8.5_gatsby-theme-childrens-picture-book
