### ISSUE TITLE
Prettier nav labels and title in the browser bar

### ISSUE THREAD

**Issue by raae** [olavea/gatsby-theme-jam-trixie-hoods-and-unicorn-lillis-revenge-on-the-pirate-princess#21]
It could happen that someone ads files starting at 02 and go forward. Or deletes a page in the middle, ie. 10. They should also be allowed to name them a, b, c, d etc. Anything that sorts. 

The code should still work.

So the path should still be the name of the file. 

But the text that is shown in the navigation and in the title bar of the browser should be the correct page number.

A solution should be to use the filename as slug/path, but then also add a label to each page context equal to its index.

**Comment by raae** [comment]
I think we should do some pair programming on this one @olavea

**Comment by olavea** [comment]
OK 😸 👍

**Comment by raae** [comment]
I did this, as I needed to clean stuff up before #25
