### ISSUE TITLE
Rename package (theme) to gatsby-theme-picture-book

### ISSUE THREAD

**Issue by raae** [olavea/gatsby-theme-jam-trixie-hoods-and-unicorn-lillis-revenge-on-the-pirate-princess#39]
Currently, the package is named `gatsby-theme-childrens-picture-book`.

Is this the best name?

**Comment by raae** [comment]
I think the package name is a little too long. My suggestion is `gatsby-theme-picture-book`.

**Comment by raae** [comment]
I have final say, yeah!

Lets call it gatsby-theme-picture-book.

**Comment by olavea** [comment]
done

**Comment by raae** [comment]
We also need to rename in all docs and the `package.json`.
