### ISSUE TITLE
Create a user on npm

### ISSUE THREAD

**Issue by raae** [olavea/gatsby-theme-jam-trixie-hoods-and-unicorn-lillis-revenge-on-the-pirate-princess#41]
You must create a user on npm.

The username is important, it can never be changed!!

I recommend creating a scoped package like me. Scoped means that my plugin starts with "@raae/".

So then your theme would be `@olavea/gatsby-theme-picture-book` or `@batcat/gatsby-theme-picture-book`. I think it is nice to have this match up with twitter and/or GitHub in some way per marketing reasons.

**Comment by olavea** [comment]
olavea
is  now username on npmjs.com
