### ISSUE TITLE
Filter out audio files from all files

### ISSUE THREAD

**Issue by raae** [olavea/gatsby-theme-jam-trixie-hoods-and-unicorn-lillis-revenge-on-the-pirate-princess#5]
Update the GraphQL query used `createPages` to include only the image files. 

```
{
  allFile(filter: {sourceInstanceName: {eq: "images"}}) {
    edges {
      node {
        name
      }
    }
  }
}
```

The "images" in the query above refers to the name in the code below from `gatsby-config.js`.

```
{
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/content/ChildrensPictureBookImages/`,
      },
    },
```

**Comment by raae** [comment]
When doing this also remove all `ignore:` stuff in `gatsby-config.js`.

And only have two `gatsby-source-filesystem`. One for the audio folder and one for the images folder.

**Comment by raae** [comment]
Also, do not use fun query names like `lillyJoanQuery`. They should be descriptive. In this case, it could be `allImageFiles`.

**Comment by olavea** [comment]
😸 👍
